### ISSUE TITLE
Error compile in v0.16.5

### ISSUE THREAD

**Issue by WuQic** [implydata/plywood#160]
```
Compiling TypeScript
node_modules/plywood-base-api/index.d.ts(1,32): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/datatypes/attributeInfo.ts(20,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/datatypes/common.ts(20,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/datatypes/dataset.ts(18,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/datatypes/set.ts(18,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/datatypes/valueStream.ts(17,27): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/expressions/baseExpression.ts(19,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/baseExpression.ts(22,45): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/expressions/joinExpression.ts(20,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/literalExpression.ts(23,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/numberBucketExpression.ts(17,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/refExpression.ts(18,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/splitExpression.ts(17,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/expressions/timePartExpression.ts(17,25): error TS7016: Could not find a declaration file for module 'moment-timezone'. '/Users/xxx/Downloads/plywood-master/node_modules/moment-timezone/index.js' implicitly has an 'any' type.
src/external/baseExternal.ts(18,69): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/external/baseExternal.ts(21,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/external/baseExternal.ts(550,29): error TS7006: Parameter 'encoding' implicitly has an 'any' type.
src/external/baseExternal.ts(550,39): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/baseExternal.ts(554,15): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/baseExternal.ts(564,37): error TS7006: Parameter 'encoding' implicitly has an 'any' type.
src/external/baseExternal.ts(564,47): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/baseExternal.ts(581,23): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/baseExternal.ts(1444,25): error TS7006: Parameter 'chunk' implicitly has an 'any' type.
src/external/baseExternal.ts(1444,32): error TS7006: Parameter 'encoding' implicitly has an 'any' type.
src/external/baseExternal.ts(1444,42): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/baseExternal.ts(1517,21): error TS7006: Parameter 'chunk' implicitly has an 'any' type.
src/external/baseExternal.ts(1517,28): error TS7006: Parameter 'enc' implicitly has an 'any' type.
src/external/baseExternal.ts(1517,33): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/druidExternal.ts(20,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/external/druidExternal.ts(22,27): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/external/druidExternal.ts(23,26): error TS7016: Could not find a declaration file for module 'stream-to-array'. '/Users/xxx/Downloads/plywood-master/node_modules/stream-to-array/index.js' implicitly has an 'any' type.
src/external/druidExternal.ts(168,14): error TS7006: Parameter 'sourcesArray' implicitly has an 'any' type.
src/external/druidExternal.ts(181,14): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/external/druidExternal.ts(189,29): error TS7006: Parameter 'encoding' implicitly has an 'any' type.
src/external/druidExternal.ts(189,39): error TS7006: Parameter 'callback' implicitly has an 'any' type.
src/external/druidSqlExternal.ts(19,26): error TS7016: Could not find a declaration file for module 'stream-to-array'. '/Users/xxx/Downloads/plywood-master/node_modules/stream-to-array/index.js' implicitly has an 'any' type.
src/external/druidSqlExternal.ts(81,14): error TS7006: Parameter 'sources' implicitly has an 'any' type.
src/external/druidSqlExternal.ts(93,14): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/external/mySqlExternal.ts(20,26): error TS7016: Could not find a declaration file for module 'stream-to-array'. '/Users/xxx/Downloads/plywood-master/node_modules/stream-to-array/index.js' implicitly has an 'any' type.
src/external/mySqlExternal.ts(73,14): error TS7006: Parameter 'sources' implicitly has an 'any' type.
src/external/mySqlExternal.ts(84,14): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/external/postgresExternal.ts(19,26): error TS7016: Could not find a declaration file for module 'stream-to-array'. '/Users/xxx/Downloads/plywood-master/node_modules/stream-to-array/index.js' implicitly has an 'any' type.
src/external/postgresExternal.ts(87,14): error TS7006: Parameter 'sources' implicitly has an 'any' type.
src/external/postgresExternal.ts(95,14): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/external/sqlExternal.ts(19,27): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/external/utils/druidAggregationBuilder.ts(17,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/helper/concurrentLimitRequester.ts(18,29): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/helper/retryRequester.ts(19,29): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/helper/streamBasics.ts(17,26): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/helper/streamBasics.ts(27,12): error TS2339: Property 'emit' does not exist on type 'ReadableError'.
src/helper/streamConcat.ts(17,37): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
src/helper/streamConcat.ts(39,12): error TS2339: Property 'push' does not exist on type 'StreamConcat'.
src/helper/streamConcat.ts(42,55): error TS2339: Property 'emit' does not exist on type 'StreamConcat'.
src/helper/utils.ts(17,29): error TS7016: Could not find a declaration file for module 'has-own-prop'. '/Users/xxx/Downloads/plywood-master/node_modules/has-own-prop/index.js' implicitly has an 'any' type.
src/helper/utils.ts(18,48): error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/xxx/Downloads/plywood-master/node_modules/readable-stream/readable.js' implicitly has an 'any' type.
```

**Comment by lorem--ipsum** [comment]
Have you ran `tdi` after having installed the node dependencies ?

**Comment by WuQic** [comment]
@lorem--ipsum 
1. clone the master
1. npm i
1. run  ./compile

**Comment by lorem--ipsum** [comment]
Please run `tdi` and try to compile again


On March 10, 2017 at 11:37:09, WuQic (notifications@github.com) wrote:

@lorem--ipsum <https://github.com/lorem--ipsum>

   1. clone the master
   2. npm i
   3. run ./compile

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/implydata/plywood/issues/160#issuecomment-285635747>,
or mute the thread

**Comment by WuQic** [comment]
thanks! prepublish
